/**
 * 027AUTO - Dados mockados baseados no Portal do Lojista Localiza (Serra - ES)
 * Estrutura inspirada em: https://portaldolojista.localiza.com/carros?cidades=874
 */

const DADOS_027AUTO = {
  // Localização padrão (Serra - ES, código 874)
  localizacao: {
    cidade: "Serra",
    estado: "ES",
    codigo: 874
  },

  // Cidades disponíveis para filtro (inspirado em https://portaldolojista.localiza.com/carros)
  // Digite na busca para filtrar (ex: "es" mostra cidades do ES)
  cidades: [
    { id: 874, nome: "Serra", estado: "ES" },
    { id: 3205309, nome: "Vitória", estado: "ES" },
    { id: 3205010, nome: "Vila Velha", estado: "ES" },
    { id: 3201308, nome: "Cariacica", estado: "ES" },
    { id: 3200169, nome: "Aracruz", estado: "ES" },
    { id: 3550308, nome: "São Paulo", estado: "SP" },
    { id: 3509502, nome: "Campinas", estado: "SP" },
    { id: 3518800, nome: "Guarulhos", estado: "SP" },
    { id: 3548708, nome: "Santo André", estado: "SP" },
    { id: 3547809, nome: "Santos", estado: "SP" },
    { id: 3550704, nome: "Sorocaba", estado: "SP" },
    { id: 3516200, nome: "Franca", estado: "SP" },
    { id: 3543402, nome: "Ribeirão Preto", estado: "SP" },
    { id: 3501608, nome: "Americana", estado: "SP" },
    { id: 3525904, nome: "Jundiaí", estado: "SP" },
    { id: 3304557, nome: "Rio de Janeiro", estado: "RJ" },
    { id: 3301702, nome: "Duque de Caxias", estado: "RJ" },
    { id: 3300100, nome: "Angra dos Reis", estado: "RJ" },
    { id: 3106200, nome: "Belo Horizonte", estado: "MG" },
    { id: 3124104, nome: "Contagem", estado: "MG" },
    { id: 3136702, nome: "Juiz de Fora", estado: "MG" },
    { id: 3170206, nome: "Uberlândia", estado: "MG" },
    { id: 4106902, nome: "Curitiba", estado: "PR" },
    { id: 4113700, nome: "Londrina", estado: "PR" },
    { id: 4100103, nome: "Maringá", estado: "PR" },
    { id: 4119905, nome: "Ponta Grossa", estado: "PR" },
    { id: 4314902, nome: "Porto Alegre", estado: "RS" },
    { id: 4313409, nome: "Pelotas", estado: "RS" },
    { id: 4323002, nome: "Santa Maria", estado: "RS" },
    { id: 4314407, nome: "Passo Fundo", estado: "RS" },
    { id: 4205407, nome: "Florianópolis", estado: "SC" },
    { id: 4202404, nome: "Blumenau", estado: "SC" },
    { id: 4216602, nome: "Joinville", estado: "SC" },
    { id: 5300108, nome: "Brasília", estado: "DF" },
    { id: 5208707, nome: "Goiânia", estado: "GO" },
    { id: 5201405, nome: "Anápolis", estado: "GO" },
    { id: 5002704, nome: "Campo Grande", estado: "MS" },
    { id: 5000203, nome: "Aquidauana", estado: "MS" },
    { id: 5103403, nome: "Cuiabá", estado: "MT" },
    { id: 5102678, nome: "Barra do Garças", estado: "MT" },
    { id: 1302603, nome: "Manaus", estado: "AM" },
    { id: 1501402, nome: "Belém", estado: "PA" },
    { id: 2304400, nome: "Fortaleza", estado: "CE" },
    { id: 2408102, nome: "Natal", estado: "RN" },
    { id: 2507507, nome: "João Pessoa", estado: "PB" },
    { id: 2611606, nome: "Recife", estado: "PE" },
    { id: 2927408, nome: "Salvador", estado: "BA" },
    { id: 2930709, nome: "Simões Filho", estado: "BA" },
    { id: 2111300, nome: "São Luís", estado: "MA" },
    { id: 2211001, nome: "Teresina", estado: "PI" },
    { id: 2704302, nome: "Maceió", estado: "AL" },
    { id: 2800308, nome: "Aracaju", estado: "SE" }
  ],

  // Marcas e modelos para filtros
  marcas: [
    { id: "fiat", nome: "Fiat", modelos: ["Argo", "Cronos", "Mobi", "Strada", "Toro", "Uno"] },
    { id: "chevrolet", nome: "Chevrolet", modelos: ["Onix", "Onix Plus", "Tracker", "Cruze"] },
    { id: "volkswagen", nome: "Volkswagen", modelos: ["Polo", "T-Cross", "Nivus", "Saveiro", "Gol"] },
    { id: "renault", nome: "Renault", modelos: ["Kwid", "Sandero", "Duster", "Logan"] },
    { id: "jeep", nome: "Jeep", modelos: ["Renegade", "Compass", "Commander"] },
    { id: "hyundai", nome: "Hyundai", modelos: ["HB20", "HB20S", "Creta"] },
    { id: "ford", nome: "Ford", modelos: ["Ka", "EcoSport", "Ranger"] }
  ],

  // Catálogo de veículos (Serra - ES)
  veiculos: [
    {
        "id": 189393,
        "marca": "VOLKSWAGEN",
        "modelo": "SAVEIRO",
        "versao": "ROBUST 1.6 16V TOTAL FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 10564,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/189393/90d161c9-ae7f-42ee-adaf-7f18b83ce934.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/189393/90d161c9-ae7f-42ee-adaf-7f18b83ce934.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "PICK-UP",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 225018,
        "marca": "RENAULT",
        "modelo": "KWID",
        "versao": "ZEN 1.0 12V SCE FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 12177,
        "preco": 0,
        "cor": "VERMELHO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225018/68cc1e7f-6523-4cd5-9ce5-c1289321006d.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225018/68cc1e7f-6523-4cd5-9ce5-c1289321006d.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 180364,
        "marca": "FIAT",
        "modelo": "MOBI",
        "versao": "LIKE 1.0 8V FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2023,
        "km": 20043,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/180364/4d84c348-a5c8-4cf5-a8f2-d5dbbe644920.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/180364/4d84c348-a5c8-4cf5-a8f2-d5dbbe644920.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 194031,
        "marca": "VOLKSWAGEN",
        "modelo": "POLO",
        "versao": "1.0 12V MPI FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 21025,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/194031/b8164e72-1d4c-4612-8ad4-35834a6a04e4.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/194031/b8164e72-1d4c-4612-8ad4-35834a6a04e4.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 185155,
        "marca": "FIAT",
        "modelo": "STRADA",
        "versao": "NOVA ENDURANCE CABINE PLUS 1.4 8V FLEX MANUAL",
        "anoFab": 2022,
        "anoMod": 2023,
        "km": 23382,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/185155/6384e159-7e43-495a-aa4c-302256896009.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/185155/6384e159-7e43-495a-aa4c-302256896009.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "PICK-UP",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 172349,
        "marca": "VOLKSWAGEN",
        "modelo": "POLO",
        "versao": "TRACK 1.0 12V FLEX - SM MANUAL",
        "anoFab": 2024,
        "anoMod": 2024,
        "km": 23585,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/172349/610a1ca8-1d7d-4668-8762-ed5117e179ea.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/172349/610a1ca8-1d7d-4668-8762-ed5117e179ea.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 163564,
        "marca": "FIAT",
        "modelo": "STRADA",
        "versao": "NOVA ENDURANCE CABINE PLUS 1.4 8V FLEX MANUAL",
        "anoFab": 2022,
        "anoMod": 2023,
        "km": 30503,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/163564/6418d7d2-fed6-435c-8de2-2251340ce904.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/163564/6418d7d2-fed6-435c-8de2-2251340ce904.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "PICK-UP",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 209951,
        "marca": "VOLKSWAGEN",
        "modelo": "NIVUS",
        "versao": "COMFORTLINE 1.0 200 TSI 12V TOTAL FLEX - AUTOMATICO",
        "anoFab": 2024,
        "anoMod": 2024,
        "km": 31198,
        "preco": 0,
        "cor": "PRETO",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/209951/d26408ba-fb64-429f-991a-b39d3643c439.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/209951/d26408ba-fb64-429f-991a-b39d3643c439.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SUV",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 194288,
        "marca": "VOLKSWAGEN",
        "modelo": "SAVEIRO",
        "versao": "ROBUST 1.6 16V TOTAL FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 31541,
        "preco": 0,
        "cor": "PRATA",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/194288/e9a66e5f-7401-466d-8e1f-f788d0ca68d6.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/194288/e9a66e5f-7401-466d-8e1f-f788d0ca68d6.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "PICK-UP",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 199756,
        "marca": "RENAULT",
        "modelo": "KWID",
        "versao": "ZEN 1.0 12V SCE FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 34291,
        "preco": 0,
        "cor": "PRATA",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/199756/5c4b20e5-e1a4-4f3d-b2eb-616f98b6e021.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/199756/5c4b20e5-e1a4-4f3d-b2eb-616f98b6e021.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 210173,
        "marca": "HYUNDAI",
        "modelo": "HB20",
        "versao": "COMFORT PLUS FLEX 1.0 MANUAL",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 34784,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/210173/27e45c55-a642-4ea2-879c-c7512b60f488.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/210173/27e45c55-a642-4ea2-879c-c7512b60f488.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 197188,
        "marca": "HYUNDAI",
        "modelo": "HB20",
        "versao": "SENSE 1.0 12V FLEX MANUAL",
        "anoFab": 2022,
        "anoMod": 2023,
        "km": 36005,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/197188/ce16634e-0358-4cca-9745-cd529b19e03b.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/197188/ce16634e-0358-4cca-9745-cd529b19e03b.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 210094,
        "marca": "FIAT",
        "modelo": "ARGO",
        "versao": "DRIVE 1.0 6V FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 36025,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/210094/a3d53c2a-4d1b-413d-a030-4598582c97b0.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/210094/a3d53c2a-4d1b-413d-a030-4598582c97b0.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 192006,
        "marca": "FIAT",
        "modelo": "MOBI",
        "versao": "TREKKING 1.0 8V FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 36934,
        "preco": 0,
        "cor": "PRATA",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/192006/c8310312-ec2e-4cef-a3b1-84d6ae0cdab0.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/192006/c8310312-ec2e-4cef-a3b1-84d6ae0cdab0.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 200173,
        "marca": "VOLKSWAGEN",
        "modelo": "POLO",
        "versao": "1.0 12V TSI FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 37631,
        "preco": 0,
        "cor": "CINZA",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/200173/0c2c2cd1-a562-4efe-bdd7-9fc76b5302e0.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/200173/0c2c2cd1-a562-4efe-bdd7-9fc76b5302e0.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 200179,
        "marca": "VOLKSWAGEN",
        "modelo": "SAVEIRO",
        "versao": "ROBUST 1.6 16V TOTAL FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2024,
        "km": 37752,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/200179/df5d8b47-cbab-43f9-bc62-f978eee1b126.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/200179/df5d8b47-cbab-43f9-bc62-f978eee1b126.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "PICK-UP",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 193694,
        "marca": "HYUNDAI",
        "modelo": "HB20",
        "versao": "COMFORT PLUS TGDI FLEX 1.0 AUTOMATICO",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 37764,
        "preco": 0,
        "cor": "PRATA",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/193694/f7b59ff8-c2e5-4ff1-bd6c-056d11846708.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/193694/f7b59ff8-c2e5-4ff1-bd6c-056d11846708.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 203060,
        "marca": "VOLKSWAGEN",
        "modelo": "SAVEIRO",
        "versao": "ROBUST 1.6 16V TOTAL FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 38322,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/203060/06f492e5-f930-45dc-8e4c-cffc03cc424c.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/203060/06f492e5-f930-45dc-8e4c-cffc03cc424c.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "PICK-UP",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 173790,
        "marca": "FIAT",
        "modelo": "STRADA",
        "versao": "NOVA ENDURANCE CABINE PLUS 1.4 8V FLEX MANUAL",
        "anoFab": 2022,
        "anoMod": 2023,
        "km": 38768,
        "preco": 0,
        "cor": "PRATA",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/173790/a07dd9d1-36ea-42af-bc89-e7d02c3d2b10.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/173790/a07dd9d1-36ea-42af-bc89-e7d02c3d2b10.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "PICK-UP",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 172173,
        "marca": "RENAULT",
        "modelo": "KWID",
        "versao": "ZEN 1.0 12V SCE FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 39169,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/172173/4bdbd9a9-1ded-4c19-ac58-130fa311cd23.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/172173/4bdbd9a9-1ded-4c19-ac58-130fa311cd23.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 182429,
        "marca": "VOLKSWAGEN",
        "modelo": "POLO",
        "versao": "TRACK 1.0 12V FLEX - SM MANUAL",
        "anoFab": 2024,
        "anoMod": 2024,
        "km": 39412,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/182429/b4cab1ef-da75-4200-87b3-a5eb92f295e5.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/182429/b4cab1ef-da75-4200-87b3-a5eb92f295e5.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 189699,
        "marca": "FIAT",
        "modelo": "ARGO",
        "versao": "DRIVE 1.0 6V FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 39737,
        "preco": 0,
        "cor": "PRETO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/189699/62455f63-b7c6-4052-82fb-f79b57dd62a0.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/189699/62455f63-b7c6-4052-82fb-f79b57dd62a0.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 181325,
        "marca": "FIAT",
        "modelo": "ARGO",
        "versao": "DRIVE 1.0 6V FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 39743,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/181325/6c98a801-ea93-4763-b0ed-ec24ce2358b2.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/181325/6c98a801-ea93-4763-b0ed-ec24ce2358b2.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 189264,
        "marca": "FIAT",
        "modelo": "ARGO",
        "versao": "DRIVE 1.0 6V FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 40259,
        "preco": 0,
        "cor": "PRETO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/189264/4139aa08-9637-44ee-9307-eecc96affc4d.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/189264/4139aa08-9637-44ee-9307-eecc96affc4d.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 209130,
        "marca": "JEEP",
        "modelo": "COMPASS",
        "versao": "LONGITUDE 1.3 16V TURBO 270 FLEX - AUTOMATICO",
        "anoFab": 2023,
        "anoMod": 2023,
        "km": 40405,
        "preco": 0,
        "cor": "PRETO",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/209130/480adea4-13a3-44bb-90b9-dd7d2f958872.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/209130/480adea4-13a3-44bb-90b9-dd7d2f958872.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SUV",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 179198,
        "marca": "RENAULT",
        "modelo": "DUSTER",
        "versao": "INTENSE 1.6 16V SCE FLEX - AUTOMATICO",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 40522,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/179198/ec772c9d-6024-4a49-826f-ddc65e61f4db.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/179198/ec772c9d-6024-4a49-826f-ddc65e61f4db.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SUV",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 181216,
        "marca": "FIAT",
        "modelo": "ARGO",
        "versao": "DRIVE 1.0 6V FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 40761,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/181216/f118051c-8eec-4610-a296-699a81971662.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/181216/f118051c-8eec-4610-a296-699a81971662.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 203071,
        "marca": "FIAT",
        "modelo": "MOBI",
        "versao": "LIKE 1.0 8V FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2024,
        "km": 40790,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/203071/23591cc0-cfcc-416a-957f-2ff073d45d66.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/203071/23591cc0-cfcc-416a-957f-2ff073d45d66.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 169088,
        "marca": "VOLKSWAGEN",
        "modelo": "POLO",
        "versao": "1.0 12V MPI FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 40830,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/169088/3ade5d8d-8a09-4b4f-8133-7ab3b2554e05.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/169088/3ade5d8d-8a09-4b4f-8133-7ab3b2554e05.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 203783,
        "marca": "HYUNDAI",
        "modelo": "HB20",
        "versao": "COMFORT PLUS FLEX 1.0 MANUAL",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 41086,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/203783/d1ebe724-5a7a-484c-a9bd-dff1d65e1c7b.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/203783/d1ebe724-5a7a-484c-a9bd-dff1d65e1c7b.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 225020,
        "marca": "VOLKSWAGEN",
        "modelo": "POLO",
        "versao": "TRACK 1.0 12V FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 41134,
        "preco": 0,
        "cor": "CINZA",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225020/0fb896a9-eb23-4e92-9ce8-006c251a4b01.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225020/0fb896a9-eb23-4e92-9ce8-006c251a4b01.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 218895,
        "marca": "FIAT",
        "modelo": "MOBI",
        "versao": "LIKE 1.0 8V FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 41594,
        "preco": 0,
        "cor": "PRATA",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/218895/081e9aff-215e-4f2b-aae9-b8a5dab96808.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/218895/081e9aff-215e-4f2b-aae9-b8a5dab96808.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 186411,
        "marca": "VOLKSWAGEN",
        "modelo": "POLO",
        "versao": "TRACK 1.0 12V FLEX - SM MANUAL",
        "anoFab": 2024,
        "anoMod": 2024,
        "km": 41815,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/186411/6fd08495-c4ee-45a1-93e2-0a4fc0f19443.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/186411/6fd08495-c4ee-45a1-93e2-0a4fc0f19443.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 174504,
        "marca": "FIAT",
        "modelo": "MOBI",
        "versao": "TREKKING 1.0 8V FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 42033,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/174504/2764e618-6761-44a6-8c3a-a8cefe708096.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/174504/2764e618-6761-44a6-8c3a-a8cefe708096.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 183128,
        "marca": "VOLKSWAGEN",
        "modelo": "POLO",
        "versao": "TRACK 1.0 12V FLEX - SM MANUAL",
        "anoFab": 2024,
        "anoMod": 2024,
        "km": 42398,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/183128/cf130714-0120-4cda-a59a-4e995353543b.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/183128/cf130714-0120-4cda-a59a-4e995353543b.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 225026,
        "marca": "VOLKSWAGEN",
        "modelo": "T-CROSS",
        "versao": "COMFORTLINE 1.0 200 TSI 12V TOTAL FLEX - AUTOMATICO",
        "anoFab": 2024,
        "anoMod": 2024,
        "km": 42456,
        "preco": 0,
        "cor": "PRATA",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225026/9e8d7d5f-561e-4f73-9cb8-8bcf8fe863f3.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225026/9e8d7d5f-561e-4f73-9cb8-8bcf8fe863f3.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SUV",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 181818,
        "marca": "FIAT",
        "modelo": "FIORINO",
        "versao": "ENDURANCE 1.4 EVO FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 42621,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/181818/4b61f583-8afb-4405-96b3-bc7ad60abfc1.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/181818/4b61f583-8afb-4405-96b3-bc7ad60abfc1.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "FURGAO",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 225025,
        "marca": "FIAT",
        "modelo": "TORO",
        "versao": "FREEDOM 1.3 16V TURBO 270 FLEX - AUTOMATICO",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 42686,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225025/fe31713b-6fb8-4b64-a6e0-09c3b07edc26.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225025/fe31713b-6fb8-4b64-a6e0-09c3b07edc26.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "PICK-UP",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 189299,
        "marca": "HYUNDAI",
        "modelo": "HB20S",
        "versao": "PLATINUM SAFETY TGDI FLEX 1.0 AUTOMATICO",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 43570,
        "preco": 0,
        "cor": "PRETO",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/189299/18ee01fd-19ea-4019-9e24-355fc79ee87a.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/189299/18ee01fd-19ea-4019-9e24-355fc79ee87a.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SEDAN",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 195801,
        "marca": "JEEP",
        "modelo": "COMPASS",
        "versao": "LONGITUDE 1.3 16V TURBO 270 FLEX - AUTOMATICO",
        "anoFab": 2023,
        "anoMod": 2023,
        "km": 43678,
        "preco": 0,
        "cor": "PRETO",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/195801/d82e7b74-0979-446e-bb30-0a89313aa76e.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/195801/d82e7b74-0979-446e-bb30-0a89313aa76e.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SUV",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 185461,
        "marca": "FIAT",
        "modelo": "ARGO",
        "versao": "DRIVE 1.0 6V FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2024,
        "km": 43864,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/185461/e3090713-9e18-41b9-a36c-47d8922fb7bb.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/185461/e3090713-9e18-41b9-a36c-47d8922fb7bb.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 198601,
        "marca": "VOLKSWAGEN",
        "modelo": "POLO",
        "versao": "1.0 12V TSI FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 43921,
        "preco": 0,
        "cor": "CINZA",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/198601/6689c8cb-f6e3-4bd9-9775-4a2e14ecb61c.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/198601/6689c8cb-f6e3-4bd9-9775-4a2e14ecb61c.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 158706,
        "marca": "FIAT",
        "modelo": "ARGO",
        "versao": "DRIVE 1.0 6V FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2024,
        "km": 44173,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/158706/fb91a3c9-bc3e-4d2c-8c34-e8c99fc315a5.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/158706/fb91a3c9-bc3e-4d2c-8c34-e8c99fc315a5.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 140028,
        "marca": "PEUGEOT",
        "modelo": "PARTNER",
        "versao": "RAPID BUSINESS PACK 1.4 8V EVO FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 44430,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/140028/60428d7e-a879-4706-aa58-7b908de1b311.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/140028/60428d7e-a879-4706-aa58-7b908de1b311.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "FURGAO",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 211744,
        "marca": "CHEVROLET",
        "modelo": "TRACKER",
        "versao": "PREMIER 1.2 12V TURBO FLEX - AUTOMATICO",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 44498,
        "preco": 0,
        "cor": "CINZA",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/211744/20a406a4-6484-48ce-9bc4-457e99ad02b2.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/211744/20a406a4-6484-48ce-9bc4-457e99ad02b2.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SUV",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 225019,
        "marca": "VOLKSWAGEN",
        "modelo": "T-CROSS",
        "versao": "HIGHLINE 1.4 250 TSI 16V TOTAL FLEX - AUTOMATICO",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 44823,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225019/39e1880b-9fa2-44b4-8f63-fc9905c712da.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225019/39e1880b-9fa2-44b4-8f63-fc9905c712da.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SUV",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 169436,
        "marca": "CHEVROLET",
        "modelo": "ONIX",
        "versao": "LT 1.0 12V FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 45031,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/169436/b454d330-c6d9-42c0-a74e-9e64036feb09.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/169436/b454d330-c6d9-42c0-a74e-9e64036feb09.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 225024,
        "marca": "VOLKSWAGEN",
        "modelo": "T-CROSS",
        "versao": "HIGHLINE 1.4 250 TSI 16V TOTAL FLEX - AUTOMATICO",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 45216,
        "preco": 0,
        "cor": "PRATA",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225024/65d73f26-cc47-4722-bb51-58fc82bcfdd4.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225024/65d73f26-cc47-4722-bb51-58fc82bcfdd4.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SUV",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 209724,
        "marca": "JEEP",
        "modelo": "COMPASS",
        "versao": "LONGITUDE 1.3 16V TURBO 270 FLEX - AUTOMATICO",
        "anoFab": 2024,
        "anoMod": 2024,
        "km": 45263,
        "preco": 0,
        "cor": "AZUL",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/209724/57babb58-8f35-4245-8288-233c62fb5158.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/209724/57babb58-8f35-4245-8288-233c62fb5158.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SUV",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 225015,
        "marca": "VOLKSWAGEN",
        "modelo": "VIRTUS",
        "versao": "12V TSI FLEX 1.0 MANUAL",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 45361,
        "preco": 0,
        "cor": "CINZA",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225015/fb4a5d7b-9957-41d5-a455-4a2b44359c19.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225015/fb4a5d7b-9957-41d5-a455-4a2b44359c19.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SEDAN",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 225027,
        "marca": "VOLKSWAGEN",
        "modelo": "T-CROSS",
        "versao": "1.0 200 TSI 12V TOTAL FLEX - AUTOMATICO",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 45537,
        "preco": 0,
        "cor": "PRETO",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225027/e7ad850b-b1d3-4f52-8ec6-3adf6a1c2781.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225027/e7ad850b-b1d3-4f52-8ec6-3adf6a1c2781.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SUV",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 163830,
        "marca": "FIAT",
        "modelo": "ARGO",
        "versao": "DRIVE 1.0 6V FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 45594,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/163830/90873f30-6fd0-4b3b-957e-9d95a41441cc.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/163830/90873f30-6fd0-4b3b-957e-9d95a41441cc.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 162162,
        "marca": "FIAT",
        "modelo": "ARGO",
        "versao": "DRIVE 1.0 6V FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2024,
        "km": 46100,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/162162/330ef303-3da5-49d1-b3d2-20fa006344e9.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/162162/330ef303-3da5-49d1-b3d2-20fa006344e9.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 208155,
        "marca": "VOLKSWAGEN",
        "modelo": "POLO",
        "versao": "1.0 12V TSI FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 46599,
        "preco": 0,
        "cor": "CINZA",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/208155/5ebaabd1-6feb-48ed-9bc3-3d739d5bf11a.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/208155/5ebaabd1-6feb-48ed-9bc3-3d739d5bf11a.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 225028,
        "marca": "CHEVROLET",
        "modelo": "TRACKER",
        "versao": "LT 1.0 12V TURBO FLEX - AUTOMATICO",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 46636,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225028/1d1aa525-fae3-4a18-8723-476198570437.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225028/1d1aa525-fae3-4a18-8723-476198570437.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SUV",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 194286,
        "marca": "HYUNDAI",
        "modelo": "HB20",
        "versao": "SENSE 1.0 12V FLEX MANUAL",
        "anoFab": 2022,
        "anoMod": 2023,
        "km": 47198,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/194286/9e90045d-5bb1-4039-9d22-a6e0e53c67c5.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/194286/9e90045d-5bb1-4039-9d22-a6e0e53c67c5.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 184021,
        "marca": "VOLKSWAGEN",
        "modelo": "POLO",
        "versao": "TRACK 1.0 12V FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 47517,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/184021/ad623650-3cbc-4593-9cf2-117eb52e4e78.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/184021/ad623650-3cbc-4593-9cf2-117eb52e4e78.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 175433,
        "marca": "FIAT",
        "modelo": "ARGO",
        "versao": "DRIVE 1.0 6V FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2024,
        "km": 47575,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/175433/3df26e81-7d6f-4f73-8c20-b9f36a8804d6.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/175433/3df26e81-7d6f-4f73-8c20-b9f36a8804d6.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 225023,
        "marca": "CHEVROLET",
        "modelo": "TRACKER",
        "versao": "LT 1.0 12V TURBO FLEX - AUTOMATICO",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 47778,
        "preco": 0,
        "cor": "PRETO",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225023/c82ddafc-6651-4280-908c-5cf7e861e523.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225023/c82ddafc-6651-4280-908c-5cf7e861e523.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SUV",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 181135,
        "marca": "RENAULT",
        "modelo": "DUSTER",
        "versao": "INTENSE PLUS FLEX 1.6 AUTOMATICO",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 47805,
        "preco": 0,
        "cor": "PRATA",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/181135/cf178d5b-b452-429b-abf2-c92017ffe151.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/181135/cf178d5b-b452-429b-abf2-c92017ffe151.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SUV",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 175511,
        "marca": "RENAULT",
        "modelo": "KWID",
        "versao": "ZEN 1.0 12V SCE FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 48078,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/175511/8ae847ac-1e06-463d-a369-cdbd3f0e8cb3.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/175511/8ae847ac-1e06-463d-a369-cdbd3f0e8cb3.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 204070,
        "marca": "CHEVROLET",
        "modelo": "ONIX",
        "versao": "PLUS LTZ 1.0 12V TURBO FLEX - AUTOMATICO",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 48558,
        "preco": 0,
        "cor": "PRATA",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/204070/f50792b5-0321-4b4d-93d5-41ac476d71e7.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/204070/f50792b5-0321-4b4d-93d5-41ac476d71e7.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SEDAN",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 193672,
        "marca": "VOLKSWAGEN",
        "modelo": "POLO",
        "versao": "1.0 12V TSI FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 48896,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/193672/a8d175c2-1825-4888-85cd-cd74a6a631fd.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/193672/a8d175c2-1825-4888-85cd-cd74a6a631fd.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 151326,
        "marca": "FIAT",
        "modelo": "ARGO",
        "versao": "1.0 6V FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2024,
        "km": 48937,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/151326/9bb10609-1aa2-496e-9bfc-8d87cfadb571.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/151326/9bb10609-1aa2-496e-9bfc-8d87cfadb571.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 225030,
        "marca": "FIAT",
        "modelo": "TORO",
        "versao": "FREEDOM 1.3 16V TURBO 270 FLEX - AUTOMATICO",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 49039,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225030/0263c6da-a857-4860-b713-5f1f2488d03f.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225030/0263c6da-a857-4860-b713-5f1f2488d03f.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "PICK-UP",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 160842,
        "marca": "CHEVROLET",
        "modelo": "ONIX",
        "versao": "LT 1.0 12V FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 49065,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/160842/9e90b295-36e9-4c19-bbf1-f26e136c2906.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/160842/9e90b295-36e9-4c19-bbf1-f26e136c2906.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 181220,
        "marca": "VOLKSWAGEN",
        "modelo": "POLO",
        "versao": "TRACK 1.0 12V FLEX - SM MANUAL",
        "anoFab": 2024,
        "anoMod": 2024,
        "km": 49091,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/181220/944e927c-8d25-41a3-89b0-f9e3a0e0b848.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/181220/944e927c-8d25-41a3-89b0-f9e3a0e0b848.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 218964,
        "marca": "VOLKSWAGEN",
        "modelo": "VIRTUS",
        "versao": "12V TSI FLEX 1.0 MANUAL",
        "anoFab": 2024,
        "anoMod": 2024,
        "km": 49198,
        "preco": 0,
        "cor": "CINZA",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/218964/13d388a6-d5ba-4400-9c27-7ce250b2d652.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/218964/13d388a6-d5ba-4400-9c27-7ce250b2d652.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SEDAN",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 221041,
        "marca": "JEEP",
        "modelo": "RENEGADE",
        "versao": "LONGITUDE 1.8 16V FLEX - AUTOMATICO",
        "anoFab": 2021,
        "anoMod": 2021,
        "km": 49260,
        "preco": 0,
        "cor": "PRATA",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/221041/f37443a7-0bbe-497c-9b90-49990087c2d2.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/221041/f37443a7-0bbe-497c-9b90-49990087c2d2.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SUV",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 225022,
        "marca": "JEEP",
        "modelo": "COMMANDER",
        "versao": "LIMITED 7L 1.3 16V TURBO 270 FLEX - AUTOMATICO",
        "anoFab": 2022,
        "anoMod": 2023,
        "km": 49511,
        "preco": 0,
        "cor": "CINZA",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225022/3ff11bca-67c3-4018-bfa2-2881ed49a120.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225022/3ff11bca-67c3-4018-bfa2-2881ed49a120.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SUV",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 225032,
        "marca": "VOLKSWAGEN",
        "modelo": "SAVEIRO",
        "versao": "ROBUST 1.6 16V TOTAL FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 49660,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225032/df57efcd-3303-4c32-86e4-93c86d4f3fbf.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225032/df57efcd-3303-4c32-86e4-93c86d4f3fbf.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "PICK-UP",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 204693,
        "marca": "FIAT",
        "modelo": "ARGO",
        "versao": "DRIVE 1.0 6V FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 50116,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/204693/7901067a-2ed6-45a7-8ab2-907895df7a4b.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/204693/7901067a-2ed6-45a7-8ab2-907895df7a4b.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 225017,
        "marca": "JEEP",
        "modelo": "RENEGADE",
        "versao": "LONGITUDE 1.3 16V TURBO 270 FLEX - AUTOMATICO",
        "anoFab": 2024,
        "anoMod": 2024,
        "km": 50162,
        "preco": 0,
        "cor": "AZUL",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225017/7fd8d1a6-d00f-46c5-a43f-75e5e425b925.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225017/7fd8d1a6-d00f-46c5-a43f-75e5e425b925.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SUV",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 101133,
        "marca": "CHEVROLET",
        "modelo": "ONIX",
        "versao": "PLUS LTZ 1.0 12V TURBO FLEX - AUTOMATICO",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 50165,
        "preco": 0,
        "cor": "PRATA",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/101133/2d159b92-f0ec-4c47-a971-e25b9b27ac1c.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/101133/2d159b92-f0ec-4c47-a971-e25b9b27ac1c.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SEDAN",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 225031,
        "marca": "CHEVROLET",
        "modelo": "TRACKER",
        "versao": "LT 1.0 12V TURBO FLEX - AUTOMATICO",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 50401,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225031/67bcfce0-a0fa-42a9-998f-70b65297348e.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225031/67bcfce0-a0fa-42a9-998f-70b65297348e.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SUV",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 196129,
        "marca": "FIAT",
        "modelo": "ARGO",
        "versao": "1.0 6V FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 50602,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/196129/96bd19fe-3f81-4846-ac99-f03e39a6ff99.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/196129/96bd19fe-3f81-4846-ac99-f03e39a6ff99.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 225016,
        "marca": "CHEVROLET",
        "modelo": "TRACKER",
        "versao": "LT 1.0 12V TURBO FLEX - AUTOMATICO",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 50903,
        "preco": 0,
        "cor": "PRATA",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225016/dcc865c2-5326-4f67-ad7b-fc6b76db7110.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225016/dcc865c2-5326-4f67-ad7b-fc6b76db7110.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SUV",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 225029,
        "marca": "VOLKSWAGEN",
        "modelo": "TAOS",
        "versao": "HIGHLINE 1.4 250 TSI 16V TOTAL FLEX - AUTOMATICO",
        "anoFab": 2024,
        "anoMod": 2024,
        "km": 51664,
        "preco": 0,
        "cor": "CINZA",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225029/52f4ac3b-4657-4b79-a4ef-1137e2d283ea.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225029/52f4ac3b-4657-4b79-a4ef-1137e2d283ea.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SUV",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 178757,
        "marca": "VOLKSWAGEN",
        "modelo": "T-CROSS",
        "versao": "COMFORTLINE 1.0 200 TSI 12V TOTAL FLEX - AUTOMATICO",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 51676,
        "preco": 0,
        "cor": "CINZA",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/178757/48c2d485-6c6c-4162-9c68-6b8b2dbbfbd3.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/178757/48c2d485-6c6c-4162-9c68-6b8b2dbbfbd3.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SUV",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 186981,
        "marca": "CHEVROLET",
        "modelo": "ONIX",
        "versao": "LT 1.0 12V FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 51749,
        "preco": 0,
        "cor": "AZUL",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/186981/ff4bc19d-5a96-45aa-9a38-91aa1312f16e.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/186981/ff4bc19d-5a96-45aa-9a38-91aa1312f16e.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 211364,
        "marca": "CHEVROLET",
        "modelo": "SPIN",
        "versao": "PREMIER 7L 1.8 8V ECONOFLEX - AUTOMATICO",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 52205,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/211364/ca58ce99-cbd7-48c7-ac7e-14d6fc23e3ec.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/211364/ca58ce99-cbd7-48c7-ac7e-14d6fc23e3ec.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "MINIVAN",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 172185,
        "marca": "FIAT",
        "modelo": "ARGO",
        "versao": "DRIVE 1.0 6V FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2024,
        "km": 52788,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/172185/4637874a-14b2-4d11-9d25-304db6d82124.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/172185/4637874a-14b2-4d11-9d25-304db6d82124.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 172323,
        "marca": "HYUNDAI",
        "modelo": "HB20",
        "versao": "COMFORT PLUS FLEX 1.0 MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 53488,
        "preco": 0,
        "cor": "PRATA",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/172323/da7f5798-ed69-4394-84a2-144b6b873a56.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/172323/da7f5798-ed69-4394-84a2-144b6b873a56.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 181407,
        "marca": "FIAT",
        "modelo": "FIORINO",
        "versao": "ENDURANCE 1.4 EVO FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 55856,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/181407/69a06d08-61d6-4f10-8b27-9fe97e3eef1c.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/181407/69a06d08-61d6-4f10-8b27-9fe97e3eef1c.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "FURGAO",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 181838,
        "marca": "VOLKSWAGEN",
        "modelo": "POLO",
        "versao": "TRACK 1.0 12V FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2025,
        "km": 56056,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/181838/d728d7f4-2a0a-4815-b729-9d1d47379992.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/181838/d728d7f4-2a0a-4815-b729-9d1d47379992.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 181836,
        "marca": "FIAT",
        "modelo": "MOBI",
        "versao": "TREKKING 1.0 8V FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 56167,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/181836/efd96220-6091-438e-beb6-92444e36a643.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/181836/efd96220-6091-438e-beb6-92444e36a643.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 174323,
        "marca": "JEEP",
        "modelo": "COMPASS",
        "versao": "LONGITUDE 1.3 16V TURBO 270 FLEX - AUTOMATICO",
        "anoFab": 2023,
        "anoMod": 2023,
        "km": 58143,
        "preco": 0,
        "cor": "PRETO",
        "combustivel": "Flex",
        "cambio": "Automático",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/174323/57b14281-b6fa-4e18-8a0d-61f87ca6043a.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/portaldolojista/anuncio/174323/57b14281-b6fa-4e18-8a0d-61f87ca6043a.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SUV",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 189491,
        "marca": "VOLKSWAGEN",
        "modelo": "POLO",
        "versao": "TRACK 1.0 12V FLEX MANUAL",
        "anoFab": 2024,
        "anoMod": 2024,
        "km": 81986,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/189491/16134eeb-1b26-4695-9bc5-ac9ca14aa6b0.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/189491/16134eeb-1b26-4695-9bc5-ac9ca14aa6b0.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 225014,
        "marca": "CHEVROLET",
        "modelo": "ONIX",
        "versao": "PLUS LTZ 1.0 12V TURBO FLEX MANUAL",
        "anoFab": 2022,
        "anoMod": 2023,
        "km": 88174,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225014/93f42fc9-787a-444f-a936-0aafa8db4b1f.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/225014/93f42fc9-787a-444f-a936-0aafa8db4b1f.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "SEDAN",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 205700,
        "marca": "FIAT",
        "modelo": "MOBI",
        "versao": "LIKE 1.0 8V FLEX MANUAL",
        "anoFab": 2021,
        "anoMod": 2021,
        "km": 109861,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/205700/6a96545f-074b-4731-ac3f-1329227cad4e.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/205700/6a96545f-074b-4731-ac3f-1329227cad4e.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    },
    {
        "id": 196118,
        "marca": "FIAT",
        "modelo": "MOBI",
        "versao": "LIKE 1.0 8V FLEX MANUAL",
        "anoFab": 2023,
        "anoMod": 2024,
        "km": 169088,
        "preco": 0,
        "cor": "BRANCO",
        "combustivel": "Flex",
        "cambio": "Mecânico",
        "motor": "1.0",
        "imagem": "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/196118/f18ed279-1823-4dbc-ada2-cb450fbf0e2b.jpg",
        "imagens": [
            "https://cdn-portal-lojista.localiza.com/prd/portaldolojista/anuncio/196118/f18ed279-1823-4dbc-ada2-cb450fbf0e2b.jpg"
        ],
        "cidade": "SERRA",
        "estado": "ES",
        "label": "HATCH",
        "descricao": "Veículo seminovo Localiza. Laudo cautelar e quilometragem real. Entre em contato para mais informações.",
        "itens": []
    }
]
      cidade: "Serra",
      estado: "ES",
      label: "Picape",
      descricao: "Veículo em excelente estado. Único dono. Revisões em dia. Documentação completa. Laudo cautelar e quilometragem real.",
      itens: ["Ar-condicionado", "Direção hidráulica", "Vidros elétricos", "Trava elétrica", "Air bags", "ABS"]
    },
    {
      id: 2,
      marca: "Renault",
      modelo: "Kwid",
      versao: "Zen 1.0 Flex 12V Manual",
      anoFab: 2023,
      anoMod: 2024,
      km: 12500,
      preco: 56890,
      cor: "Vermelho",
      combustivel: "Flex",
      cambio: "Mecânico",
      motor: "1.0",
      imagem: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80",
      imagens: [
        "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80",
        "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
        "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80"
      ],
      cidade: "Serra",
      estado: "ES",
      label: "Econômico",
      descricao: "Carro econômico ideal para cidade. Baixo consumo. Laudo cautelar e quilometragem real.",
      itens: ["Ar-condicionado", "Direção elétrica", "Vidros elétricos", "USB", "Central multimídia"]
    },
    {
      id: 3,
      marca: "Fiat",
      modelo: "Mobi",
      versao: "Like 1.0 Flex Manual",
      anoFab: 2023,
      anoMod: 2023,
      km: 18500,
      preco: 52900,
      cor: "Prata",
      combustivel: "Flex",
      cambio: "Mecânico",
      motor: "1.0",
      imagem: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80",
      imagens: [
        "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80",
        "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80",
        "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&q=80"
      ],
      cidade: "Serra",
      estado: "ES",
      label: "Entrada",
      descricao: "Hatch compacto. Procedência garantida. Preço abaixo da FIPE.",
      itens: ["Ar-condicionado", "Direção elétrica", "Vidros elétricos"]
    },
    {
      id: 4,
      marca: "Volkswagen",
      modelo: "Polo",
      versao: "Comfort 200 TSI Flex Automático",
      anoFab: 2023,
      anoMod: 2024,
      km: 22000,
      preco: 99990,
      cor: "Azul",
      combustivel: "Flex",
      cambio: "Automático",
      motor: "1.0",
      imagem: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
      imagens: [
        "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
        "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80",
        "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80"
      ],
      cidade: "Serra",
      estado: "ES",
      label: "Sedan",
      descricao: "Sedan premium alemão. Motor TSI turbo. Documentação completa.",
      itens: ["Ar-condicionado digital", "CarPlay/Android Auto", "Câmera de ré", "Sensor de estacionamento"]
    },
    {
      id: 5,
      marca: "Fiat",
      modelo: "Strada",
      versao: "Volcyear 1.3 Flex Manual",
      anoFab: 2023,
      anoMod: 2024,
      km: 15200,
      preco: 78900,
      cor: "Preto",
      combustivel: "Flex",
      cambio: "Mecânico",
      motor: "1.3",
      imagem: "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&q=80",
      imagens: [
        "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&q=80",
        "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
        "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80"
      ],
      cidade: "Serra",
      estado: "ES",
      label: "Picape",
      descricao: "Picape versátil. Laudo cautelar. Quilometragem real.",
      itens: ["Ar-condicionado", "Direção elétrica", "Central multimídia", "USB"]
    },
    {
      id: 6,
      marca: "Fiat",
      modelo: "Argo",
      versao: "Drive 1.0 Flex",
      anoFab: 2023,
      anoMod: 2023,
      km: 15000,
      preco: 58900,
      cor: "Branco",
      combustivel: "Flex",
      cambio: "Mecânico",
      motor: "1.0",
      imagem: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
      imagens: [
        "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
        "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80",
        "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&q=80"
      ],
      cidade: "Serra",
      estado: "ES",
      label: "Hatch mais vendido",
      descricao: "Veículo em excelente estado. Único dono. Revisões em dia. Laudo cautelar e quilometragem real.",
      itens: ["Ar-condicionado", "Direção hidráulica", "Vidros elétricos", "Trava elétrica", "Air bags", "ABS", "Bluetooth"]
    },
    {
      id: 7,
      marca: "Jeep",
      modelo: "Renegade",
      versao: "Sport 1.8 Flex 4x2",
      anoFab: 2022,
      anoMod: 2023,
      km: 28000,
      preco: 98500,
      cor: "Preto",
      combustivel: "Flex",
      cambio: "Automático",
      motor: "1.8",
      imagem: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80",
      imagens: [
        "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80",
        "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
        "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80"
      ],
      cidade: "Serra",
      estado: "ES",
      label: "SUV mais vendido",
      descricao: "SUV seminovo com procedência garantida. Laudo cautelar, quilometragem real e preço abaixo da FIPE.",
      itens: ["Ar-condicionado digital", "Central multimídia", "Piloto automático", "Faróis LED", "Controle de cruzeiro"]
    },
    {
      id: 8,
      marca: "Chevrolet",
      modelo: "Onix Plus",
      versao: "Premier 1.0 Turbo Flex",
      anoFab: 2023,
      anoMod: 2023,
      km: 12000,
      preco: 62400,
      cor: "Prata",
      combustivel: "Flex",
      cambio: "Automático",
      motor: "1.0",
      imagem: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80",
      imagens: [
        "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80",
        "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
        "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80"
      ],
      cidade: "Serra",
      estado: "ES",
      label: "Popular",
      descricao: "Sedan compacto com melhor custo-benefício. Motor turbo. Revisões na concessionária.",
      itens: ["Ar-condicionado", "MyLink", "Apple CarPlay", "Câmera de ré", "Sensor de estacionamento"]
    },
    {
      id: 9,
      marca: "Volkswagen",
      modelo: "T-Cross",
      versao: "Highline 1.0 TSI",
      anoFab: 2023,
      anoMod: 2024,
      km: 20000,
      preco: 118290,
      cor: "Azul",
      combustivel: "Gasolina",
      cambio: "Automático",
      motor: "1.0",
      imagem: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
      imagens: [
        "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
        "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80",
        "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80"
      ],
      cidade: "Serra",
      estado: "ES",
      label: "SUV Compacto",
      descricao: "SUV compacto alemão. Motor 1.0 TSI turbo. Único dono, laudo cautelar.",
      itens: ["Painel digital", "Ar-condicionado digital", "CarPlay/Android Auto", "Faróis full LED"]
    },
    {
      id: 10,
      marca: "Fiat",
      modelo: "Cronos",
      versao: "Drive 1.3 Flex",
      anoFab: 2023,
      anoMod: 2023,
      km: 18500,
      preco: 75490,
      cor: "Cinza",
      combustivel: "Flex",
      cambio: "Automático",
      motor: "1.3",
      imagem: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80",
      imagens: [
        "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80",
        "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
        "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80"
      ],
      cidade: "Serra",
      estado: "ES",
      label: "Sedan",
      descricao: "Sedan econômico com porta-malas generoso. Laudo cautelar.",
      itens: ["Ar-condicionado", "Central multimídia", "USB", "Vidros elétricos"]
    },
    {
      id: 11,
      marca: "Chevrolet",
      modelo: "Tracker",
      versao: "Premier 1.2 Turbo Flex",
      anoFab: 2023,
      anoMod: 2024,
      km: 18000,
      preco: 108290,
      cor: "Branco",
      combustivel: "Flex",
      cambio: "Automático",
      motor: "1.2",
      imagem: "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&q=80",
      imagens: [
        "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&q=80",
        "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80",
        "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80"
      ],
      cidade: "Serra",
      estado: "ES",
      label: "SUV Compacto",
      descricao: "SUV compacto com tecnologia. Motor turbo 1.2. Quilometragem real e laudo cautelar.",
      itens: ["Ar-condicionado digital", "MyLink com CarPlay", "Câmera 360°", "Cruze control adaptativo"]
    },
    {
      id: 12,
      marca: "Volkswagen",
      modelo: "Nivus",
      versao: "Highline 200 TSI Flex",
      anoFab: 2023,
      anoMod: 2024,
      km: 9500,
      preco: 117990,
      cor: "Vermelho",
      combustivel: "Flex",
      cambio: "Automático",
      motor: "1.0",
      imagem: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80",
      imagens: [
        "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80",
        "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
        "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&q=80"
      ],
      cidade: "Serra",
      estado: "ES",
      label: "SUV",
      descricao: "SUV-crossover com design arrojado. Motor TSI. Procedência garantida.",
      itens: ["Painel digital", "Ar-condicionado digital", "CarPlay", "Faróis LED"]
    },
    {
      id: 13,
      marca: "Fiat",
      modelo: "Argo",
      versao: "Drive 1.0 Flex",
      anoFab: 2024,
      anoMod: 2025,
      km: 2227,
      preco: 69900,
      cor: "Preto",
      combustivel: "Flex",
      cambio: "Mecânico",
      motor: "1.0",
      imagem: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
      imagens: [
        "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
        "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80"
      ],
      cidade: "Goiânia",
      estado: "GO",
      label: "Hatch",
      descricao: "Veículo novo, quase zero km. Procedência Localiza.",
      itens: ["Ar-condicionado", "Direção elétrica", "Bluetooth", "Air bags"]
    },
    {
      id: 14,
      marca: "Hyundai",
      modelo: "HB20",
      versao: "Evolution 1.0 Flex",
      anoFab: 2023,
      anoMod: 2024,
      km: 18000,
      preco: 72900,
      cor: "Prata",
      combustivel: "Flex",
      cambio: "Automático",
      motor: "1.0",
      imagem: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80",
      imagens: [
        "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80"
      ],
      cidade: "Vitória",
      estado: "ES",
      label: "Hatch",
      descricao: "Hatch popular. Laudo cautelar. Documentação em dia.",
      itens: ["Ar-condicionado", "Central multimídia", "CarPlay", "Câmera de ré"]
    },
    {
      id: 15,
      marca: "Volkswagen",
      modelo: "Polo",
      versao: "Comfort 200 TSI Flex",
      anoFab: 2023,
      anoMod: 2023,
      km: 25000,
      preco: 94900,
      cor: "Branco",
      combustivel: "Flex",
      cambio: "Automático",
      motor: "1.0",
      imagem: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
      imagens: [
        "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80"
      ],
      cidade: "Vila Velha",
      estado: "ES",
      label: "Sedan",
      descricao: "Sedan alemão. Quilometragem real. Preço abaixo da FIPE.",
      itens: ["Ar-condicionado", "CarPlay", "Sensor de estacionamento"]
    },
    {
      id: 16,
      marca: "Chevrolet",
      modelo: "Onix",
      versao: "Plus Premier 1.0 Turbo Flex",
      anoFab: 2024,
      anoMod: 2024,
      km: 5000,
      preco: 78900,
      cor: "Azul",
      combustivel: "Flex",
      cambio: "Automático",
      motor: "1.0",
      imagem: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80",
      imagens: [
        "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80"
      ],
      cidade: "São Paulo",
      estado: "SP",
      label: "Popular",
      descricao: "Quase zero km. Único dono. Documentação completa.",
      itens: ["Ar-condicionado digital", "MyLink", "CarPlay", "Câmera de ré"]
    }
  ],

  // Dados de cadastro/lojista (mock)
  cadastro: {
    lojista: {
      nome: "Revenda 027",
      cnpj: "00.000.000/0001-00",
      email: "contato@revenda027.com.br",
      telefone: "(27) 3000-0000",
      endereco: {
        logradouro: "Av. Principal, 1000",
        bairro: "Centro",
        cidade: "Serra",
        estado: "ES",
        cep: "29160-000"
      },
      contratoAtivo: true,
      limiteCredito: 500000
    },
    colaboradores: [
      { id: 1, nome: "João Silva", email: "joao@revenda027.com.br", perfil: "Admin" },
      { id: 2, nome: "Maria Santos", email: "maria@revenda027.com.br", perfil: "Operador" }
    ]
  }
};
